src/costs/urls.py
from django.urls import path
from .views import (
    CostCreateView,
    CostsListView,
    CostDeleteView,
    CostDetailView,
    CostUpdateView,
)

app_name = 'costs'
urlpatterns = [
    path('', CostsListView.as_view(), name='costs-list'),
    path('create/', CostCreateView.as_view(), name='cost-create'),
    path('<int:id>/', CostDetailView.as_view(), name='cost-detail'),
    path('<int:id>/update/', CostUpdateView.as_view(), name='cost-update'),
    path('<int:id>/delete/', CostDeleteView.as_view(), name='cost-delete'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
# from homepage.views import home_screen_view
from orders.views import OrdersListView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', OrdersListView.as_view(), name="home"),
    path('costs/', include('costs.urls')),
    path('orders/', include('orders.urls')),
    path('products/', include('products.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path
from .views import (
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductsListView,
    ProductUpdateView,
)

app_name = 'products'
urlpatterns = [
    path('', ProductsListView.as_view(), name='products-list'),
    path('create/', ProductCreateView.as_view(), name='product-create'),
    path('<int:id>/', ProductDetailView.as_view(), name='product-detail'),
    path('<int:id>/update/',
         ProductUpdateView.as_view(), name='product-update'),
    path('<int:id>/delete/',
         ProductDeleteView.as_view(), name='product-delete'),
]

src/products/models.py
from decimal import Decimal
from django.db import models
from django.urls import reverse


class Product(models.Model):

    HEIGHT = 'H'
    WIDTH = 'W'
    PERIMETER = 'P'
    NONE = 'NA'
    MULTIPLIERS_CHOICES = [
        (HEIGHT, 'Largo'),
        (WIDTH, 'Ancho'),
        (PERIMETER, 'Perímetro'),
        (NONE, 'Nada'),
    ]

    name = models.CharField(max_length=150)

    # Cost
    making_cost = models.DecimalField(
        verbose_name="Costo confección",
        max_digits=50, decimal_places=2, default=0)
    making_multiplier = models.CharField(
        verbose_name="Factor medida multiplicadora costo confección",
        max_length=2, choices=MULTIPLIERS_CHOICES, default=NONE)
    making_factor = models.DecimalField(
        verbose_name="Factor costo confección",
        default=None, blank=True, null=True, max_digits=50, decimal_places=2)
    making_tolerance = models.DecimalField(
        verbose_name="Tolerancia costo confección",
        default=None, blank=True, null=True,
        max_digits=50, decimal_places=2)

    # 1st Component
    material_1 = models.ForeignKey(
        "costs.Cost", verbose_name="Materia prima componente 1",
        on_delete=models.CASCADE, default=None, blank=True, null=True,
        related_name="prod_raw_material_comp_1")
    multiplier_1 = models.CharField(
        verbose_name="Factor medida multiplicadora componente 1",
        max_length=2, choices=MULTIPLIERS_CHOICES, default=NONE)
    factor_1 = models.DecimalField(
        verbose_name="Factor componente 1",
        default=None, blank=True, null=True,
        max_digits=50, decimal_places=2)
    tolerance_1 = models.DecimalField(
        verbose_name="Tolerancia componente 1",
        default=None, blank=True, null=True,
        max_digits=50, decimal_places=2)

    # 2nd Component
    material_2 = models.ForeignKey(
        "costs.Cost", verbose_name="Materia prima componente 2",
        on_delete=models.CASCADE, default=None, blank=True, null=True,
        related_name="prod_raw_material_comp_2")
    multiplier_2 = models.CharField(
        verbose_name="Factor medida multiplicadora componente 2",
        max_length=2, choices=MULTIPLIERS_CHOICES, default=NONE)
    factor_2 = models.DecimalField(
        verbose_name="Factor componente 2",
        default=None, blank=True, null=True,
        max_digits=50, decimal_places=2)
    tolerance_2 = models.DecimalField(
        verbose_name="Tolerancia componente 2",
        default=None, blank=True, null=True,
        max_digits=50, decimal_places=2)

    # 3rd Component
    material_3 = models.ForeignKey(
        "costs.Cost", verbose_name="Materia prima componente 3",
        on_delete=models.CASCADE, default=None, blank=True, null=True,
        related_name="prod_raw_material_comp_3")
    multiplier_3 = models.CharField(
        verbose_name="Factor medida multiplicadora componente 3",
        max_length=2, choices=MULTIPLIERS_CHOICES, default=NONE)
    factor_3 = models.DecimalField(
        verbose_name="Factor componente 3",
        default=None, blank=True, null=True,
        max_digits=50, decimal_places=2)
    tolerance_3 = models.DecimalField(
        verbose_name="Tolerancia componente 3",
        default=None, blank=True, null=True,
        max_digits=50, decimal_places=2)

    def dictify(self, component, multiplier, factor, tolerance):
        return {
            'cost': Decimal(component),
            'multiplier': multiplier,
            'factor': factor,
            'tolerance': tolerance,
        }

    def components_as_dicts(self):
        result = []

        if self.making_cost != 0:
            making = self.dictify(
                self.making_cost, self.making_multiplier,
                self.making_factor, self.making_tolerance)
            result.append(making)

        if self.material_1 is not None:
            comp_1 = self.dictify(
                self.material_1.price, self.multiplier_1,
                self.factor_1, self.tolerance_1)
            result.append(comp_1)

        if self.material_2 is not None:
            comp_2 = self.dictify(
                self.material_2.price, self.multiplier_2,
                self.factor_2, self.tolerance_2)
            result.append(comp_2)

        if self.material_3 is not None:
            comp_3 = self.dictify(
                self.material_3.price, self.multiplier_3,
                self.factor_3, self.tolerance_3)
            result.append(comp_3)

        return result

    def get_component_total(self, component: dict, measures: dict):
        cost = Decimal(component['cost'])

        mult_by = component['multiplier']
        if mult_by is self.NONE:
            return cost

        factor = Decimal(component['factor'])
        measure = Decimal(measures[mult_by])

        if factor == 1:
            return cost * measure

        tolerance = Decimal(component['tolerance'])
        times_it_fits = Decimal(int(measure/factor))

        reminder = Decimal(measure) - Decimal(times_it_fits * factor)
        percent_reminder = reminder * Decimal(100) / factor

        if percent_reminder > tolerance:
            times_it_fits += 1
        return cost * times_it_fits

    def get_price(self, width, height):
        total = Decimal(0)
        for component in self.components_as_dicts():
            subtotal = self.get_component_total(
                component, self.get_measures_dict(width, height))
            total += subtotal
        return total

    def net_worth(self, width, height):
        if self.making_cost == 0:
            return 0
        making = self.dictify(
            self.making_cost, self.making_multiplier,
            self.making_factor, self.making_tolerance)
        measures = self.get_measures_dict(width, height)
        return self.get_component_total(making, measures)

    def get_perimeter(self, width, height):
        return (width * Decimal(2)) + (height * Decimal(2))

    def get_measures_dict(self, width, height):
        return {
            self.HEIGHT: height,
            self.WIDTH: width,
            self.PERIMETER: self.get_perimeter(width, height),
            self.NONE: Decimal(0)
        }

    def get_absolute_url(self):
        return reverse("products:product-detail", kwargs={"id": self.id})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"

src/products/forms.py
from django import forms

from .models import Product


class ProductModelForm(forms.ModelForm):

    making_tolerance = forms.DecimalField(
        label='Tolerancia costo confección',
        label_suffix=" (en porcentaje)",
        required=False)
    tolerance_1 = forms.DecimalField(
        label='Tolerancia componente 1',
        label_suffix=" (en porcentaje)",
        required=False)
    tolerance_2 = forms.DecimalField(
        label='Tolerancia componente 2',
        label_suffix=" (en porcentaje)",
        required=False)
    tolerance_3 = forms.DecimalField(
        label='Tolerancia componente 3',
        label_suffix=" (en porcentaje)",
        required=False)

    class Meta:
        model = Product
        fields = [
            'name',
            'making_cost',
            'making_multiplier',
            'making_factor',
            'making_tolerance',
            'material_1',
            'multiplier_1',
            'factor_1',
            'tolerance_1',
            'material_2',
            'multiplier_2',
            'factor_2',
            'tolerance_2',
            'material_3',
            'multiplier_3',
            'factor_3',
            'tolerance_3',
        ]

src/products/views.py
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView
)
from .forms import ProductModelForm
from .models import Product


class ProductCreateView(CreateView):
    template_name = 'products/product_create.html'
    form_class = ProductModelForm
    queryset = Product.objects.all()

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


class ProductsListView(ListView):
    template_name = 'products/products_list.html'
    queryset = Product.objects.all()


class ProductDetailView(DetailView):
    template_name = 'products/product_detail.html'

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Product, id=id_)


class ProductUpdateView(UpdateView):
    template_name = 'products/product_create.html'
    form_class = ProductModelForm

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Product, id=id_)

    def form_valid(self, form):
        return super().form_valid(form)


class ProductDeleteView(DeleteView):
    template_name = 'products/product_delete.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Product, id=id_)

    def get_success_url(self):
        return reverse('products:products-list')

src/products/templates/products/product_create.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .cont {
        margin: 30px;
    }
</style>

<div class="cont">
    <h3>Nuevo Producto</h3>
    <form action='.' method='POST'>{% csrf_token %}
        {{ form.as_p }}
        <input type='submit' class="btn btn-success" value='Guardar' />
        <a class="btn btn-secondary" href='../'>Cancelar</a>
    </form>
</div>

{% endblock content %}

src/products/templates/products/product_delete.html
{% extends 'base.html' %}

{% block content %}


<form action='.' method='POST'>{% csrf_token %}
    <h4>¿Querés eliminar "{{ object.name }}"?</h4>
    <br>
    <p>
        <input type='submit' value='Eliminar' class="btn btn-danger" />
        <a class="btn btn-secondary" href='../'>Cancelar</a>
    </p>
</form>


{% endblock %}

src/products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}

{% load currency_extras %}

<h3>{{ object.name }}</h3>
<hr style="max-width: 800px;">


<!-- COSTO CONFECCIÓN -->
{% if object.making_cost > 0 %}
<p>
    <strong>Costo confección:</strong> {{ object.making_cost|currencier }}
    {% if object.making_multiplier != 'NA' %}
    x {{ object.get_making_multiplier_display }}
    {% if object.making_factor != 1 %}
    /{{ object.making_factor }}
    {% if object.making_tolerance > 0 %}
    @{{ object.making_tolerance }}
    {% endif %}
    {% endif %}
    {% endif %}
</p>
{% endif %}


<!-- COMPONENTE N°1 -->
{% if object.material_1 %}
<p>
    <strong>Componente N°1:</strong> {{ object.material_1.name }} {{ object.material_1.price|currencier }}
    {% if object.multiplier_1 != 'NA' %}
    x {{ object.get_multiplier_1_display }}
    {% if object.factor_1 != 1 %}
    /{{ object.factor_1 }}
    {% if object.tolerance_1 > 0 %}
    @{{ object.tolerance_1 }}
    {% endif %}
    {% endif %}
    {% endif %}
</p>
{% endif %}


<!-- COMPONENTE N°2 -->
{% if object.material_2 %}
<p>
    <strong>Componente N°2:</strong> {{ object.material_2.name }} {{ object.material_2.price|currencier }}
    {% if object.multiplier_2 != 'NA' %}
    x {{ object.get_multiplier_2_display }}
    {% if object.factor_2 != 1 %}
    /{{ object.factor_2 }}
    {% if object.tolerance_2 > 0 %}
    @{{ object.tolerance_2 }}
    {% endif %}
    {% endif %}
    {% endif %}
</p>
{% endif %}


<!-- COMPONENTE N°3 -->
{% if object.material_3 %}
<p>
    <strong>Componente N°3</strong> {{ object.material_3.name }} {{ object.material_3.price|currencier }}
    {% if object.multiplier_3 != 'NA' %}
    x {{ object.get_multiplier_3_display }}
    {% if object.factor_3 != 1 %}
    /{{ object.factor_3 }}
    {% if object.tolerance_3 > 0 %}
    @{{ object.tolerance_3 }}
    {% endif %}
    {% endif %}
    {% endif %}
</p>
{% endif %}
<hr style="max-width: 800px;">

<button onclick="location.href = '{% url 'products:product-update' id=object.id %}'"
    class="btn btn-primary">Editar</button>
<button onclick="location.href = '{% url 'products:product-delete' id=object.id %}'"
    class="btn btn-danger">Eliminar</button>
<a href='../'> Volver</a>

{% endblock %}

src/products/templates/products/products_list.html
{% extends 'base.html' %}


{% block content %}

<h3>Productos</h3>
{% if object_list|length > 0 %}
<div>
    <table class="table table-hover w-auto">
        <thead class=" table-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
            </tr>
        </thead>
        <tbody>
            {% for instance in object_list %}
            {% include 'products/snippets/product_item.html' with product=instance %}
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<p>
    No se agregaron productos. Podés agregar uno haciendo click <a href="{% url 'products:product-create' %}">aquí</a>.
</p>
{% endif %}

{% endblock content %}