src/account/urls.py
from django.urls import path
from .views import AccountUpdateView


app_name = 'account'
urlpatterns = [

    # Order
    path('<int:id>/', AccountUpdateView.as_view(), name='update'),
    # path('create/', OrderCreateView.as_view(), name='order-create'),
    # path('<int:id>/', get_order_detail_view, name='order-detail'),
    # path('<int:id>/update/', OrderUpdateView.as_view(), name='order-update'),
    # path('<int:id>/delete/', OrderDeleteView.as_view(), name='order-delete'),
]

src/costs/urls.py
from django.urls import path
from .views import (
    CostCreateView,
    CostsListView,
    CostDeleteView,
    CostDetailView,
    CostUpdateView,
)

app_name = 'costs'
urlpatterns = [
    path('', CostsListView.as_view(), name='costs-list'),
    path('create/', CostCreateView.as_view(), name='cost-create'),
    path('<int:id>/', CostDetailView.as_view(), name='cost-detail'),
    path('<int:id>/update/', CostUpdateView.as_view(), name='cost-update'),
    path('<int:id>/delete/', CostDeleteView.as_view(), name='cost-delete'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
# from homepage.views import home_screen_view
from orders.views import OrdersListView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', OrdersListView.as_view(), name="home"),
    path('costs/', include('costs.urls')),
    path('orders/', include('orders.urls')),
    path('products/', include('products.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path
from .views import (
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductsListView,
    ProductUpdateView,
)

app_name = 'products'
urlpatterns = [
    path('', ProductsListView.as_view(), name='products-list'),
    path('create/', ProductCreateView.as_view(), name='product-create'),
    path('<int:id>/', ProductDetailView.as_view(), name='product-detail'),
    path('<int:id>/update/',
         ProductUpdateView.as_view(), name='product-update'),
    path('<int:id>/delete/',
         ProductDeleteView.as_view(), name='product-delete'),
]

src/templates/snippets/base_css.html
<style type="text/css">
    body {
        background-color: #f2f2f2;
        font-family: Roboto;
        padding-top: 5rem;
    }
</style>

src/templates/snippets/footer.html
<style type="text/css">
    .footer {
        min-height: 100px;
    }
</style>

<!-- Footer -->
<br>
<div class="d-flex flex-row align-items-center footer  bg-white border-top shadow-lg">
    <p class="m-auto">EkoSoftware | 2021</p>
</div>
<!-- End Footer -->

<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script> -->

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
</script>

src/templates/snippets/nav.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
    <a class="navbar-brand">Entretelas</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navContent"
        aria-controls="navContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Presupuestos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'products:products-list' %}">Productos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'costs:costs-list' %}">Costos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Calculadora</a>
            </li>
        </ul>
        <div class="mt-2 mt-md-0">

            {% if request.user.is_authenticated %}
            <a class="p-2" href="{% url 'account:update' id=request.user.id %}">Account</a>
            <a class="p-2 btn btn-danger" href="#">Logout</a>
            {% else %}
            <button class="btn btn-success my-2 my-sm-0" type="submit">Register</button>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Login</button>
            {% endif %}

        </div>
    </div>
</nav>