src/costs/urls.py
from django.urls import path
from .views import (
    CostCreateView,
    CostsListView,
    CostDeleteView,
    CostDetailView,
    CostUpdateView,
)

app_name = 'costs'
urlpatterns = [
    path('', CostsListView.as_view(), name='costs-list'),
    path('create/', CostCreateView.as_view(), name='cost-create'),
    path('<int:id>/', CostDetailView.as_view(), name='cost-detail'),
    path('<int:id>/update/', CostUpdateView.as_view(), name='cost-update'),
    path('<int:id>/delete/', CostDeleteView.as_view(), name='cost-delete'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
# from homepage.views import home_screen_view
from orders.views import OrdersListView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', OrdersListView.as_view(), name="home"),
    path('costs/', include('costs.urls')),
    path('orders/', include('orders.urls')),
    path('products/', include('products.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/orders/urls.py
from django.urls import path
from .views import (
    ItemCreateView,
    ItemDeleteView,
    ItemUpdateView,
    FabricCreateView,
    FabricDeleteView,
    FabricUpdateView,
    OrderCreateView,
    OrderDeleteView,
    OrderUpdateView,
    get_order_detail_view,
    PaymentCreateView,
    PaymentDeleteView,
    PaymentUpdateView,
    generate_pdf_report,
)

app_name = 'orders'
urlpatterns = [

    # Order
    path('create/', OrderCreateView.as_view(), name='order-create'),
    path('<int:id>/', get_order_detail_view, name='order-detail'),
    path('<int:id>/update/', OrderUpdateView.as_view(), name='order-update'),
    path('<int:id>/delete/', OrderDeleteView.as_view(), name='order-delete'),
    # Generate pdf report
    path('<int:id>/print', generate_pdf_report, name="pdf-report"),

    # Items
    path('<int:id>/add-item/', ItemCreateView.as_view(),
         name='order-add-item'),
    path('<int:id>/delete-item/<int:item>', ItemDeleteView.as_view(),
         name='order-delete-item'),
    path('<int:id>/update-item/<int:item>', ItemUpdateView.as_view(),
         name='order-update-item'),

    # Fabrics
    path('<int:id>/add-fabric/', FabricCreateView.as_view(),
         name='order-add-fabric'),
    path('<int:id>/delete-fabric/<int:fabric>', FabricDeleteView.as_view(),
         name='order-delete-fabric'),
    path('<int:id>/update-fabric/<int:fabric>', FabricUpdateView.as_view(),
         name='order-update-fabric'),

    # Payments
    path('<int:id>/add-payment/', PaymentCreateView.as_view(),
         name='order-add-payment'),
    path('<int:id>/delete-payment/<int:payment>', PaymentDeleteView.as_view(),
         name='order-delete-payment'),
    path('<int:id>/update-payment/<int:payment>', PaymentUpdateView.as_view(),
         name='order-update-payment'),


]

src/orders/models.py
import locale
from decimal import Decimal
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator


locale.setlocale(locale.LC_ALL, 'es_ar')


class Order(models.Model):

    NEW = "NE"
    WAITING_ANSWER = "ER"
    ACCEPTED = "AC"
    MAKING = "MK"
    FINISHED = "FI"
    STATES = [
        (NEW, 'Nuevo'),
        (WAITING_ANSWER, 'Esperando respuesta'),
        (ACCEPTED, 'Aceptado'),
        (MAKING, 'En confección'),
        (FINISHED, 'Terminado'),
    ]

    customer_first_name = models.CharField(
        max_length=100, verbose_name="Nombre")
    customer_last_name = models.CharField(
        max_length=100, verbose_name="Apellido",
        default=None, blank=True, null=True)
    customer_email = models.EmailField(
        max_length=254, verbose_name="Email",
        default=None, blank=True, null=True)
    customer_tel = models.CharField(
        max_length=50, verbose_name="Teléfono",
        default=None, blank=True, null=True)
    customer_city = models.CharField(
        max_length=50, verbose_name="Localidad",
        default=None, blank=True, null=True)
    customer_zip_code = models.CharField(
        max_length=50, verbose_name="Código Postal",
        default=None, blank=True, null=True)
    customer_state = models.CharField(
        max_length=50, verbose_name="Provincia",
        default=None, blank=True, null=True)
    creation_date = models.DateTimeField(
        verbose_name="creation date", auto_now_add=True)
    last_edited = models.DateTimeField(
        verbose_name="Última edición", auto_now=True)
    expiration_date = models.DateField(
        verbose_name="Fecha de expiración",
        default=None, blank=True, null=True)
    state = models.CharField(
        max_length=1, choices=STATES, default=NEW,
        verbose_name="Estado")
    discount = models.DecimalField(
        verbose_name="Porcentaje de descuento por confección",
        decimal_places=2, max_digits=5,
        default=None, blank=True, null=True)

    def get_absolute_url(self):
        return reverse("orders:order-detail", kwargs={"id": self.id})

    def get_balances(self, items, fabrics, payments):
        items_total = Decimal(0)
        net_worth = Decimal(0)
        items_prices = {}
        for item in items:
            t = item.calculate_total()
            items_total += t
            nw = item.get_net_worth()
            net_worth += nw
            items_prices[item.id] = t

        fabrics_total = Decimal(0)
        for fabric in fabrics:
            fabrics_total += fabric.total()

        payments_total = Decimal(0)
        print('payments', payments)
        for payment in payments:
            payments_total += payment.get_amount()
            # print('payment something', payment.get_am)

        total = items_total + fabrics_total
        left_balance = total - payments_total
        return {
            'items_total': items_total,
            'items_prices': items_prices,
            'fabrics_total': fabrics_total,
            'total': total,
            'payments_total': payments_total+Decimal(0),
            'left_balance': left_balance,
            'net_worth': net_worth,
        }

    def __str__(self):
        return f'{self.id}-{self.creation_date}'

    class Meta:
        verbose_name = "Order"
        verbose_name_plural = "Orders"


class Item(models.Model):

    order = models.ForeignKey(
        Order, verbose_name='Pedido',
        on_delete=models.CASCADE, related_name='items')

    product = models.ForeignKey(
        'products.Product', verbose_name='Producto',
        on_delete=models.CASCADE, null=False)

    height = models.DecimalField(
        verbose_name='Largo', max_digits=10, decimal_places=2, default=0)
    width = models.DecimalField(
        verbose_name='Ancho', max_digits=10, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(
        verbose_name='Cantidad', default=1,
        validators=[MinValueValidator(1), MaxValueValidator(9999)])

    def get_width(self):
        return Decimal(self.width)

    def get_height(self):
        return Decimal(self.height)

    def calculate_total(self):
        price = self.product.get_price(self.get_width(), self.get_height())
        self.price = price,
        return price * self.quantity

    def get_price(self):
        return self.price

    def get_net_worth(self):
        return self.product.net_worth(self.get_width(), self.get_height())

    # def get_absolute_url(self):
    #     return reverse("orders:order-detail", kwargs={"id": self.id})

    def get_q(self):
        return f'{self.quantity} unidades'

    def __str__(self):
        return f'{self.product.name} ({self.get_height()}x{self.get_width()}m)'

    class Meta:
        verbose_name = "Item"
        verbose_name_plural = "Items"


class Fabric(models.Model):

    name = models.CharField(verbose_name='Nombre', max_length=250)
    price_per_size = models.DecimalField(
        verbose_name='Precio por metro', max_digits=50, decimal_places=2)
    size = models.DecimalField(
        verbose_name='Metros (cantidad)', max_digits=50, decimal_places=2)
    order = models.ForeignKey(
        Order, verbose_name='Pedido',
        on_delete=models.CASCADE, related_name='fabrics')

    def total(self):
        pps = Decimal(self.price_per_size)
        s = Decimal(self.size)
        return pps * s

    def get_q(self):
        return f'{self.size} meters'

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Fabric"
        verbose_name_plural = "Fabrics"


class Payment(models.Model):

    CASH = "EF"
    CARD = "CA"
    CHECK = "CH"
    DEPOSIT = "DE"
    MERCADO_PAGO = "MP"
    TRANSFER = "TR"

    METHODS = [
        (CASH, 'Efectivo'),
        (CHECK, 'Cheque'),
        (DEPOSIT, 'Depósito'),
        (MERCADO_PAGO, 'MercadoPago'),
        (CARD, 'Tarjeta'),
        (TRANSFER, 'Transferencia Bancaria'),
    ]

    amount = models.DecimalField(
        verbose_name='Importe', max_digits=50, decimal_places=2, default=1)
    date = models.DateField(
        verbose_name="Fecha", default=None, blank=True, null=True)
    method = models.CharField(
        verbose_name="Medio de pago", max_length=2,
        choices=METHODS, default=CASH)
    order = models.ForeignKey(
        "orders.Order", verbose_name="Pedido",
        on_delete=models.CASCADE, related_name='payments')

    def get_amount(self):
        return Decimal(self.amount)

    def __str__(self):
        if self.date:
            return f'{self.date} - {self.amount}'
        return str(self.amount)

    class Meta:
        verbose_name = "Pago"
        verbose_name_plural = "Pagos"

src/orders/forms.py
from django import forms
# from django.forms.widgets import DateInput
from .models import Order, Item, Fabric, Payment


class OrderModelForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'customer_first_name',
            'customer_last_name',
            'customer_email',
            'customer_tel',
            'customer_city',
            'customer_zip_code',
            'customer_state',
            'discount',
        ]


class ItemModelForm(forms.ModelForm):

    order = forms.Field(required=True, disabled=True)

    class Meta:
        model = Item
        fields = [
            'order',
            'product',
            'width',
            'height',
            'quantity',
        ]


class ItemUpdateForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = [
            'product',
            'width',
            'height',
            'quantity',
        ]


class FabricModelForm(forms.ModelForm):

    order = forms.Field(required=True, disabled=True)
    price_per_size = forms.DecimalField(label_suffix=': $')

    class Meta:
        model = Fabric
        fields = [
            'name',
            'price_per_size',
            'size',
            'order',
        ]


class FabricUpdateForm(forms.ModelForm):

    price_per_size = forms.DecimalField(label_suffix=': $')

    class Meta:
        model = Fabric
        fields = [
            'name',
            'price_per_size',
            'size',
        ]


class PaymentModelForm(forms.ModelForm):

    date = forms.DateField(widget=forms.DateInput(
        format=('%Y-%m-%d'), attrs={
            'class': 'datepicker',
            'placeholder': 'Fecha',
            'type': 'date'}))
    method = forms.ChoiceField(label='Método de pago', choices=Payment.METHODS)
    amount = forms.DecimalField(label='Importe', label_suffix=': $',)
    order = forms.Field(required=True, disabled=True)

    class Meta:
        model = Payment
        fields = [
            'date',
            'method',
            'amount',
            'order',
        ]


class PaymentUpdateForm(forms.ModelForm):

    date = forms.DateField(widget=forms.DateInput(
        format=('%Y-%m-%d'), attrs={
            'class': 'datepicker',
            'placeholder': 'Fecha',
            'type': 'date'}))
    method = forms.ChoiceField(label='Método de pago', choices=Payment.METHODS)
    amount = forms.DecimalField(label='Importe', label_suffix=': $')

    class Meta:
        model = Payment
        fields = [
            'date',
            'method',
            'amount',
        ]

src/orders/templates/orders/fabric_create.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
    .cont {
        margin: 30px;
    }
</style>

<div class="cont">
    <h3>Nueva tela</h3>
    <form action='.' method='POST'>{% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Agregar' class='btn btn-success' />
        <a href="../">Cancelar</a>
    </form>
</div>

{% endblock content %}

src/orders/templates/orders/fabric_delete.html
{% extends 'base.html' %}

{% block content %}

<form method='POST'>{% csrf_token %}
    <div class="">
        <div class="d-flex justify-content-center">
            <h4>¿Querés eliminar la tela "{{ object }}"?</h4>
        </div>
        <br>
        <div class="d-flex justify-content-center">
            <br>
            <p><input type='submit' value='Sí, eliminar' class="btn btn-danger" /> <a href='../'>Cancelar</a></p>
        </div>

    </div>
</form>

{% endblock %}

src/orders/templates/orders/fabric_update.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
    .cont {
        margin: 30px;
    }
</style>

<div class="cont">
    <h3>Actualizar tela</h3>
    <form method='POST'>{% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Guardar' class="btn btn-success" />
        <a href="../">Cancelar</a>
    </form>
</div>

{% endblock content %}

src/orders/templates/orders/item_create.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
    .cont {
        margin: 30px;
    }
</style>

<div class="cont">
    <h3>Nuevo ítem</h3>
    <form action='.' method='POST'>{% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Agregar' />
    </form>
</div>

{% endblock content %}

src/orders/templates/orders/item_delete.html
{% extends 'base.html' %}

{% block content %}

<form method='POST'>{% csrf_token %}
    <div class="">
        <div class="d-flex justify-content-center">
            <h4>¿Querés eliminar el item "{{ object }}"?</h4>
        </div>
        <br>
        <div class="d-flex justify-content-center">
            <br>
            <p><input type='submit' value='Sí, eliminar' class="btn btn-danger" /> <a href='../'>Cancelar</a></p>
        </div>

    </div>
</form>

{% endblock %}

src/orders/templates/orders/item_update.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
    .cont {
        margin: 30px;
    }
</style>

<div class="cont">
    <h3>Actualizar ítem</h3>
    <form method='POST'>{% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Guardar' class="btn btn-success" />
        <a href="../">Cancelar</a>
    </form>
</div>

{% endblock content %}

src/orders/templates/orders/order_create.html
{% extends 'base.html' %}

{% block content %}

<div class="row justify-content-md-center">
    <div>
        <h3>Nuevo pedido</h3>
        <h5>Datos del/de la cliente</h5>
        <form action='.' method='POST'>{% csrf_token %}
            {{ form.as_p }}
            <input type='submit' value='Guardar' class='btn btn-success' />
            <a href="../"> Cancelar</a>
        </form>
    </div>
</div>

{% endblock content %}

src/orders/templates/orders/order_delete.html
{% extends 'base.html' %}

{% block content %}


<form method='POST'>{% csrf_token %}
    <div class="">
        <div class="d-flex justify-content-center">
            <h1>¿Querés cancelar el presupuesto N.°{{ object.id }} a nombre de {{ object.customer_first_name }}
                {{ object.customer_last_name }} creado el día {{ object.creation_date|date:"d/m/Y" }}?</h1>
        </div>
        <br>
        <div class="d-flex justify-content-center">
            <br>
            <p><input type='submit' value='Sí, cancelar' class="btn btn-danger" /> <a href='../'>No, volver</a></p>
        </div>
    </div>
</form>

{% endblock %}

src/orders/templates/orders/order_detail.html
{% extends 'base.html' %}

{% block content %}

{% load tz %}

<style type="text/css">
    .d {
        border: 3px solid;
        padding: 5px;
        margin-bottom: 5px;
        font-family: 'Roboto Slab', serif;
        font-weight: bold;
    }

    .state {
        margin: 5px;
        padding: 5px;
        font-size: 1.40em;
    }


    .subtitulos,
    th,
    h1,
    h5 {
        font-family: 'Roboto Slab', serif;
    }

    h1,
    h5 {
        font-weight: bold;
    }

    h1 {
        margin-right: 10px;
    }
</style>

<!-- TITLES -->
<div class="row justify-content-md-center">

    {% if success == 1 %}
    <p class="success"> Actualizado con éxito. </p>
    {% endif %}

    <h1>Pedido N.° {{ order.id }} </h1>
    <span> </span>
    {% if order.state == "NE" %}
    <span class="state" style="background-color: #E33142; color: #fff;">
        {% elif order.state == "ER" %}
        <span class="state" style="background-color: #FBBF09;">
            {% elif order.state == "AC" %}
            <span class="state" style="background-color: #198754; color: #fff;">
                {% elif order.state == "MK" %}
                <span class="state" style="background-color: #106DF9; color: #fff;">
                    {% elif order.state == "FI" %}
                    <span class="state" style="background-color: #6C757D; color: #fff;">
                        {% endif %}
                        {{ order.get_state_display }}
                    </span>
</div>

<div class="row justify-content-md-center">
    <div class="col-md-center">
        {% load tz %}<p>Creado el {{ order.creation_date|timezone:"America/Buenos_Aires" }}</p>
    </div>
</div>
<!-- END TITLES -->


<!-- CUSTOMER INFO -->
<div class="row">
    <div class="col">
        <h5>Datos del/de la cliente <span>
                <button onclick="location.href='{% url 'orders:order-update' id=order.id %}';">Editar</button>
            </span></h5>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-lg-4">
        <p><b>Nombre y apellido:</b> {{ order.customer_first_name }} {{ order.customer_last_name }}</p>
    </div>
    <div class="col-xs-12 col-lg-4">
        <p>
            <b>Email:</b>
            <a href="mailto:{{ order.customer_email }}">{{ order.customer_email }}</a>
        </p>
    </div>
    <div class="col-xs-12 col-lg-4">
        <p><b>Teléfono:</b> {{ order.customer_tel }}</p>
    </div>
</div>

<br>
<!-- END CUSTOMER INFO -->


<div class="listing">

    <!-- PRODUCTOS -->
    {% load currency_extras %}

    <h5 class="subtitulos">Productos</h5>
    {% if items|length > 0 %}
    <div>
        <table class="table table-striped table-light">
            <thead class="table-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Concepto</th>
                    <th scope="col">Valor</th>
                    <th scope="col">Unidades</th>
                    <th scope="col">Total</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                {% include 'orders/snippets/item_table_item.html' with item=item counter=forloop.counter %}
                {% endfor %}
            </tbody>
            <tfoot>
                <tr class="table-dark">
                    <td></td>
                    <td colspan="2"><a href="{% url 'orders:order-add-item' id=order.id %}">+Agregas más</a></td>
                    <td><b>Subtotal:</b></td>
                    <td>{{ items_total|currencier }}</td>
                    <td scope="col"> </td>
                </tr>
            </tfoot>
        </table>
    </div>
    {% else %}
    <p>Aun no agregaste ningún producto a la lista. Agregá uno haciendo click <a
            href="{% url 'orders:order-add-item' id=order.id %}">aquí</a>.
    </p>
    {% endif %}

    <br>

    <!-- TELAS -->
    <h5 class="subtitulos">Telas</h5>
    {% if fabrics|length > 0 %}
    <div>
        <table class="table table-striped table-light">
            <thead class="table-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Precio por metro</th>
                    <th scope="col">Metros</th>
                    <th scope="col">Total</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for fabric in fabrics %}
                {% include 'orders/snippets/item_table_fabric.html' with fabric=fabric counter=forloop.counter %}
                {% endfor %}
            </tbody>
            <tfoot>
                <tr class="table-dark">
                    <td></td>
                    <td><a href="{% url 'orders:order-add-fabric' id=order.id %}">+Agregas
                            más</a>
                    </td>
                    <td></td>
                    <td><b>Subtotal:</b></td>
                    <td>{{ fabrics_total|currencier }}</td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
    </div>
    {% else %}
    <p>Aun no gastaste nada en telas. Agregá un gasto haciendo click <a
            href="{% url 'orders:order-add-fabric' id=order.id %}">aquí</a>.</p>
    {% endif %}

    <br>

    <!-- PAGOS -->
    <h5 class="subtitulos">Pagos</h5>
    {% if payments|length > 0 %}
    <div>
        <table class="table table-striped table-light">
            <thead class="table-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Fecha</th>
                    <th scope="col">Medio de pago</th>
                    <th scope="col">Importe</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for payment in payments %}
                {% include 'orders/snippets/item_table_payment.html' with payment=payment counter=forloop.counter %}
                {% endfor %}
            </tbody>
            <tfoot>
                <tr class="table-dark">
                    <td></td>
                    <td><a href="{% url 'orders:order-add-payment' id=order.id %}">+Registrar más</a></td>
                    <td><b>Subtotal:</b> </td>
                    <td>{{ payments_total|currencier }} </td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
    </div>
    {% else %}
    <p>Aun no se registraron pagos. Agregá un pago haciendo click
        <a href="{% url 'orders:order-add-payment' id=order.id %}">
            aquí
        </a>
        .
    </p>
    {% endif %}
</div>

<br>
<hr>


<div class="row justify-content-md-center">
    <div class="col-xs-12 col-lg-6">
        <!-- SALDOS -->
        <h5>
            <p><b>Total a pagar:</b> {{ total|currencier }}</p>
            <p>
                <b>Pagado:</b> -{{ payments_total|currencier }}
            </p>
            <h4><b>Saldo restante:</b> <strong>{{ left_balance|currencier }}</strong></h4>
        </h5>
    </div>
    <div class="col-xs-12 col-lg-6 text-center align-middle">
        <h5>
            Obtenés una ganancia neta de:
        </h5>
        <h1>
            <strong>{{ net_worth|currencier }}</strong>
        </h1>
    </div>

</div>

<hr>
<br>


<div>
    <!-- ACCIONES -->
    <div>
        {% if order.expiration_date %}
        Fecha de vencimiento: {{ order.expiration_date|date:"d/m/Y" }}
        <button class="btn btn-primary">Reimprimir presupuesto</button>
        {% else %}
        <button class="btn btn-primary" onclick="location.href='{% url 'orders:pdf-report' id=order.id%}';">
            Imprimir presupuesto
        </button>
        {% endif %}
        <button class="btn btn-secondary" onclick="location.href='{% url 'orders:order-delete' id=order.id %}';">
            Cancelar presupuesto
        </button>
    </div>

    <p>{{ order.expiraton_date }}</p>

</div>


{% endblock %}

src/orders/templates/orders/order_list.html
{% extends 'base.html' %}


{% block content %}
<div class="row justify-content-md-center">
    <div class="col">
        <h3>Presupuestos en curso</h3>
        {% if object_list|length > 0 %}

        <table class="table table-striped table-light">
            <thead class="table-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Estado</th>
                    <th scope="col">Nombre y Apellido</th>
                    <th scope="col">Fecha de creación</th>
                    <th scope="col">Fecha de vencimiento</th>
                </tr>
            </thead>
            <tbody>
                {% for instance in object_list %}
                {% if instance.state != "FI" %}
                {% include 'orders/snippets/item_order.html' with instance=instance %}
                {% endif %}
                {% endfor %}
            </tbody>
        </table>

        {% else %}
        <p>No se agregaron presupuesto. Podés agregar uno haciendo click <a
                href="{% url 'orders:order-create' %}">aquí</a>.
        </p>
        {% endif %}

        <a href="{% url 'orders:order-create' %}">+Crear uno nuevo</a>
    </div>
</div>

{% endblock content %}

src/orders/templates/orders/payment_create.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .cont {
        margin: 30px;
        background-color: #f2f2f2;
        max-width: 400px;
    }
</style>


<div class="row justify-content-md-center">
    <div>
        <h3>Nuevo pago</h3>
        <form action='.' method='POST'>{% csrf_token %}
            {{ form.as_p }}
            <input type='submit' value='Agregar' class='btn btn-success' />
            <a href="../">Cancelar</a>
        </form>
    </div>
</div>


{% endblock content %}

src/orders/templates/orders/payment_delete.html
{% extends 'base.html' %}

{% block content %}

{% load currency_extras %}

<form method='POST'>{% csrf_token %}
    <div class="">
        <div class="d-flex justify-content-center">
            {% load tz %}
            <h4>¿Querés eliminar el pago por {{ object.amount|currencier }} del día
                {{ object.date|date:"d/m/Y" }}?</h4>
        </div>
        <br>
        <div class="d-flex justify-content-center">
            <br>
            <p><input type='submit' value='Sí, eliminar' class="btn btn-danger" /> <a href='../'>Cancelar</a></p>
        </div>

    </div>
</form>

{% endblock %}

src/orders/templates/orders/payment_update.html
{% extends 'base.html' %}


{% block content %}

<div class="row justify-content-md-center">
    <div>
        <h3>Actualizar pago</h3>
        <form method='POST'>{% csrf_token %}
            {{ form.as_p }}
            <input type='submit' value='Guardar' class='btn btn-success' />
            <a href="../">Cancelar</a>
        </form>
    </div>
</div>

{% endblock content %}